project_id = "vgvebpchxvnoawgqnudc"

[functions.evaluate-answer]
verify_jwt = false

[functions.manage-assignment]
verify_jwt = false

[functions.class-insights]
verify_jwt = false

[functions.voice-explain]
verify_jwt = false

[functions.transcribe-voice]
verify_jwt = false
